blog/urls.py
# blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path("", views.BlogPostListView.as_view(), name="blogpost_list"),
    path(
        "create/", views.BlogPostCreateView.as_view(), name="blogpost_create"
    ),  # URL для создания поста
    path("<slug:slug>/", views.BlogPostDetailView.as_view(), name="blogpost_detail"),
    path(
        "<slug:slug>/update/",
        views.BlogPostUpdateView.as_view(),
        name="blogpost_update",
    ),
    path(
        "<slug:slug>/delete/",
        views.BlogPostDeleteView.as_view(),
        name="blogpost_delete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from catalog import views as catalog_views # Импортируем представления из приложения catalog под псевдонимом catalog_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),  # Главная страница
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("contacts/", catalog_views.contacts, name="contacts"),  # Страница контактов в приложении catalog
    path("product/", catalog_views.ProductlistView.as_view(), name="product_list"),  # Маршрут для product_list
    path("users/", include("users.urls")),  # Пути для работы с пользователями (регистрация, логин и т.д.)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterUserView, CustomLoginView, CustomLogoutView, email_verification

app_name = 'users'

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),  # Регистрация пользователя
    path('login/', CustomLoginView.as_view(), name='login'),  # Логин пользователя
    path('logout/', CustomLogoutView.as_view(), name='logout'),  # Логин пользователя
    path('email_confirm/<str:token>', email_verification, name='email-confirm'),  # Верификация почты
]

templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="/product/">Продукты</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="/admin/">Вход для админа</a>
    </nav>
    <!-- Кнопки регистрации и входа -->
    <div class="ms-3">
        {% if user.is_authenticated %}
            <a> {{ user }} </a>
            <a class="btn btn-secondary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="btn btn-primary me-2" href="{% url 'users:register' %}">Регистрация</a>
            <a class="btn btn-secondary" href="{% url 'users:login' %}">Вход</a>
        {% endif %}
    </div>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>